site_name: ISYS
site_url: https://dreamem0ra1n.github.io/ISYS
repo_url: https://github.com/dreamem0ra1n/ISYS
repo_name: ISYS

nav:
  - 首页: index.md
  - 专业基础:
      - 数据结构基础: 专业基础/数据结构基础.md
      - 面向对象程序设计: 专业基础/面向对象程序设计.md
  - 专业必修: 
      - 计算机系统Ⅰ: 专业必修/计算机系统Ⅰ.md
      - 信息安全原理与数学基础: 专业必修/信息安全原理与数学基础.md
      - 高级数据结构与算法分析: 专业必修/高级数据结构与算法分析.md
      - 计算机系统Ⅱ: 专业必修/计算机系统Ⅱ.md
      - 数据安全与密码学基础: 专业必修/数据安全与密码学基础.md
      - 计算机系统Ⅲ: 专业必修/计算机系统Ⅲ.md
      - 隐私计算与数据合规: 专业必修/隐私计算与数据合规.md
      - 计算机网络: 专业必修/计算机网络.md
      - 软件安全原理和实践: 专业必修/软件安全原理和实践.md
      - 系统安全原理与实践: 专业必修/系统安全原理与实践.md
      - 网络安全原理与实践: 专业必修/网络安全原理与实践.md
      - 无线与物联网安全基础: 专业必修/无线与物联网安全基础.md
  - 专业选修:
      - 应用基础类: 
        - 汇编语言程序设计与调试: 专业选修/应用基础类/汇编语言程序设计与调试.md
        - 网络空间安全导论: 专业选修/应用基础类/网络空间安全导论.md
        - 数据库系统: 专业选修/应用基础类/数据库系统.md
        - 面向信息安全的信号处理: 专业选修/应用基础类/面向信息安全的信号处理.md
        - 多媒体安全: 专业选修/应用基础类/多媒体安全.md
        - 信息安全管理: 专业选修/应用基础类/信息安全管理.md
      - 实践拓展类:
        - 计算理论: 专业选修/实践拓展类/计算理论.md
        - 量子计算理论基础与软件系统: 专业选修/实践拓展类/量子计算理论基础与软件系统.md
        - 专题研讨: 专业选修/实践拓展类/专题研讨.md
        - 计算机科学思想史: 专业选修/实践拓展类/计算机科学思想史.md
        - 区块链安全与数字货币原理: 专业选修/实践拓展类/区块链安全与数字货币原理.md
        - 职业发展规划讲座: 专业选修/实践拓展类/职业发展规划讲座.md
        - 社交网络安全与隐私: 专业选修/实践拓展类/社交网络安全与隐私.md
  - 实践教学:
      - CTF101: 实践教学/信息安全课程综合实践(CTF101).md
      - 信息安全产业实践: 实践教学/信息安全产业实践.md
  - 专业进阶: 
      - 软件保护技术: 专业进阶/软件保护技术.md
      - 硬件安全基础: 专业进阶/硬件安全基础.md
      - 编程语言原理: 专业进阶/编程语言原理.md
      - 密码学进阶: 专业进阶/密码学进阶.md
      - 编译原理: 专业进阶/编译原理.md
      - 人工智能安全: 专业进阶/人工智能安全.md
      - 深度合成技术与电子取证: 专业进阶/深度合成技术与电子取证.md
  - 杂项:
      - 更新记录和计划: 杂项/更新记录和计划.md
      - 工作流和信息渠道: 杂项/工作流和信息渠道.md

theme:
  name: material
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
  font:
    code: JetBrains Mono
    text: JetBrains Mono
  palette:
    primary: cyan
    accent: light blue

  features:
    - navigation.sidebar
    - content.action.edit
    - content.code.copy
    - content.tabs
    - navigation.tracking
    - navigation.expand
    - navigation.top
    - navigation.footer
    - tags

plugins:
  - search
  - git-revision-date-localized:
      type: date
      timezone: Asia/Shanghai
      locale: zh
      enable_creation_date: false
  - macros:
      module_name: scripts/main

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences

extra_css:
  - css/style.css

extra:
  comments:
    enabled: true # 启用评论
    mode: giscus # 使用 Giscus 作为评论系统
